### ISSUE TITLE
a question?

### ISSUE THREAD

**Issue by onlyonewater** [escorciav/daps#10]
hi, authors, @escorciav  I want to reduce the video dimension from (num_frames, ori_dimension) to (num_frames, new_dimension), and I find that in the readme, you give an example, like this, I want to know what the means about 'U', could you explain it? thanks!!
![image](https://github.com/escorciav/daps/assets/41667733/2b7ab003-a4c2-4180-9d04-b3e52b697fd1)

**Comment by escorciav** [comment]
SVD decomposition :). Don't trust the convention. It could be that I made a typo switching U & V 😉
