### ISSUE TITLE
How to run your code without conda?

### ISSUE THREAD

**Issue by RyanCV** [escorciav/daps#2]
Hi, I can't install conda, how to run your code without conda?? Thanks.

**Comment by escorciav** [comment]
Hi,

Thanks for your interest in our work and sorry for the late reply.

To run code without conda, you need to install all the dependencies listed [here](https://github.com/escorciav/daps/blob/master/environment_x64.yml). Follow the [installation steps](https://github.com/escorciav/daps/blob/master/install.sh#L38-L39) concerning pip to get theano and lasagne.

We also added the dependencies listed by pip [here](https://github.com/escorciav/daps/blob/master/requirements.txt) for these cases. Note that, we have not tested the code by running `pip install -r requirements.txt `. Feel free to comment your findings here.

All the best!

Victor
