### ISSUE TITLE
NMS for Action Proposal Inference

### ISSUE THREAD

**Issue by LuoweiZhou** [escorciav/daps#3]
In the code the non-maximum suppression threshold for inference is set to [0.7](https://github.com/escorciav/daps/blob/9ed84bfba9e29231d2e1f51b9d153b7fd8afec7e/daps/utils/segment.py#L139), while in the paper, that value is 0.3 (for [action detection](https://ivul.kaust.edu.sa/Documents/Publications/2016/DAPs%20Deep%20Action%20Proposals%20for%20Action%20Understanding.pdf)).

So, I assume action detection requires less sparse proposals? Thank you!

**Comment by escorciav** [comment]
Hi Luowei!

We were checking our code and we found that the implementation of NMS used for action detection is different to the function provided here. In summary, the NMS threshold used for action detection was 0.7 but our code at that stage was using "1 - tIOU" for removing candidates.

Thanks for the note 😉 

Eager to read more interesting findings from your work.

Victor
