### ISSUE TITLE
Error loading for hdf5 file

### ISSUE THREAD

**Issue by h19920918** [escorciav/daps#4]
Thank you to share your code and contribution.

My problem is when I use data/sample/c3d_after_pca.hdf5, It doesn't work with printing some error message.

Command :
python tools/generate_proposals.py -iv video_test_0000541 -ic3d data/samples/c3d_after_pca.hdf5 -imd data/models/T512K64_thumos14.npz

Error line and its message :
    with h5py.File(self.filename, 'r') as fobj: -> self.filename = data/samples/c3d_after_pca.hdf5
    print IOError: IOError(...found)',)

Could you advise to me why does it happen?
Maybe, It is highly basic question but I don't have any experience to deal with .hdf5 file format.

**Comment by escorciav** [comment]
Hi @h19920918,
we are glad to hear about your interest in our work.
I'm really sorry to hear that. People have reached us before with problems dealing with HDF5. My advices:
- Make sure that you download the file appropriately.
- Test that the file is not corrupted. You can use something like `$ h5ls -l [filename]`.
  - `h5ls` is a binary installed along with HDF5 in some distros.
  - replace `[filename]` by the name of the file.
- It seems that the error stack is incomplete. I guess that the file does not exist.
  - I always do `$ ls [file]` after I receive this kind of error.

I hope these comments give you a hint. Good luck!
Victor

_Side note_
> __Why HDF5?__
Pickle and NPY are terrible for python 2&3 compatibility. We went for something more standard and easily supported by python (even several other languages).

_Extra note_
> `$` means execute in a shell

**Comment by h19920918** [comment]
Thank @escorciav for your reply.

I tried to execute **h5ls -l c3d_after_pca.hdf5** provided by you and its output is **"unable to open file"**

As you mentioned, I checked whether the file is corrupted or Not.
**It might be corrupted because website address in c3d_after_pca.hdf5 can't find error 404.**
So, I consider how to download this file to right way but I can't find.

When I clicked **"Download the C3D representation of a couple of videos from here."**, It printed **"Sorry about that, but we can’t show files that are this big right now".**

**So, I wonder that If when the installation is done or clone your github, whether C3D representation data is downloaded automatic or NOT.**
If it is not automatic, Please how to download the C3D representation and If the other, I will try to install again.

I'm sorry to bother you.

p.s. I am learning now how to use HDF5 file something like hello world in HDF5.
When I try to execute the code and HDF5 file provided some education website, It can works.
But the code doesn't work for c3d_after_pca.hdf file, before doing this, I check all code for opening HDF5 file such as file name, format etc..

**Comment by escorciav** [comment]
My guess is that there was an issue downloading the files.

- Try to download it (them) again.
  - double check the size, c3d_after_pca.hdf5 := 2.73 MB.
  - Check your git config. We use [git-lsf](https://git-lfs.github.com/) to store the data. Maybe, your git did not download these binaries correctly. Pls, search on the internet for more details 😉. Feel free to comment your finding here for other people.
  - Try to __download__ it directly from the GitHub website. I just did it without any problem. According to your message, it seems that you tried to open or visualize it in the browser.
- Test the file with `h5ls` before assuming that the installation went wrong.

Best,

Victor

**Comment by h19920918** [comment]
Really appreciate kindly your advice nevertheless basic question.
I will try your suggest.

Thank you.
