### ISSUE TITLE
meaning of number smaller than zero in the proposal file

### ISSUE THREAD

**Issue by vra** [escorciav/daps#7]
Hi @escorciav ,
First Thanks for your useful code, it's really helpful. When I run ` tools/generate_proposals.py`, I got output like this in csv file:
```bash
245 171 0.42824159235 lsvc020163
53 11 0.406542558764 lsvc020163
4 -4 0.382954354819 lsvc020163
27 -28 0.379393531972 lsvc020163
```
I wonder what does the negative numbers mean and can I delete these records from the proposal lists as in-normal cases?  Could you please give some hints on this? Thanks in advance.

**Comment by escorciav** [comment]
Hi!
Thanks for your interest in our work.
- There is no golden rule for your question. It really depends on the application.
- You can ignore them or trim them such that they belong to the segment where the model generates them.
- For benchmarking purposes, please use the pre-computed results mentioned in the wiki/FAQs. If we did not provide them, try your best for making a fair comparison :smile: 
Best,
