### ISSUE TITLE
Invalid hdf5 files

### ISSUE THREAD

**Issue by robonich** [escorciav/daps#8]
When I did the step 5 of [do-you-want-to-try](https://github.com/escorciav/daps#do-you-want-to-try), I found that the [file](https://github.com/escorciav/daps/blob/master/data/samples/c3d_after_pca.hdf5) of the C3D representation of a couple of videos was an invalid hdf5 because python said ```IOError: Unable to open file (File signature not found)```. I also checked the file with h5debug command and got messages below.
```
$ h5debug pca_c3d_fc7_thumos14.hdf5 
HDF5-DIAG: Error detected in HDF5 (1.8.17) thread 140267664561920:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1087 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 277 in H5F_super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
cannot open file
```
All the hdf5 files in [this folder](https://github.com/escorciav/daps/tree/master/data/models) were also invalid.
If you have free time, please reupload these sample files.

**Comment by robonich** [comment]
After I redownloaded files from url directly, I got all files correctly!
So I will close this issue.

**Comment by escorciav** [comment]
Sorry for that, I will make things easier next time.
