### ISSUE TITLE
how to use action classifier of daps

### ISSUE THREAD

**Issue by zjyalice** [escorciav/daps#9]
Hi~ 
In your paper, i find you design an action classifier to evaluate mAP for proposals,  but i don't find this code, would you mind tell me where is the code and how to use it ? 
Thank you very much! Best wishes !

**Comment by escorciav** [comment]
Hi, thanks for your interest in our work. Unfortunately, we don't have that implementation anymore. 
In our follow up project [SST](https://github.com/shyamal-b/sst), we achieved much better results by applying [SCNN classifier](https://github.com/zhengshou/scnn). Maybe, that's a simple alternative to consider.

**Comment by zjyalice** [comment]
Thanks for your reply! I will try to use the SCNN-classifier. Best wishes！
